spring.application.name=similar-products-api

server.port=5000

external.product-api.base-url=http://localhost:3001
external.product-api.timeout-ms=2000
management.endpoints.web.exposure.include=mappings
